"""Public connected CLI API assembled from focused operation modules."""

from __future__ import annotations

from .connected_approvals import (
    ApprovalDraft,
    check_health,
    create_approval,
    decide_approval,
    decide_finding,
    fetch_events,
    fetch_finding,
    fetch_policies,
    parse_approval_arguments,
    parse_event_arguments,
    parse_health_arguments,
    parse_single_argument,
    read_approval,
)
from .connected_feedback import (
    AssuranceDraft,
    FeedbackDraft,
    append_assurance,
    read_assurance,
    read_feedback_metrics,
    submit_feedback,
)
from .connected_lifecycle import (
    BackupDraft,
    DeletionDraft,
    SecretGrantDraft,
    approve_deletion,
    create_backup,
    create_deletion,
    execute_deletion,
    grant_secret,
    hold_deletion,
    read_backup,
    read_deletion,
    read_secret_grant,
    transition_backup,
)
from .connected_payload import parse_payload
from .connected_runs import (
    ConnectedCollection,
    ConnectedRunSettings,
    ResultKind,
    cancel_run,
    fetch_results,
    fetch_run,
    new_idempotency_key,
    parse_connected_arguments,
    parse_results_arguments,
    parse_run_arguments,
    render_receipt,
    resumable_idempotency_key,
    run_connected,
    settings_from_environment,
    timestamp,
)
from .connected_transport import (
    ConnectedApi,
    ConnectedCliError,
    ConnectedCliErrorCode,
    ConnectedRunReceipt,
    ConnectedRunRequest,
    HttpConnectedApi,
)

__all__ = [
    "ApprovalDraft",
    "AssuranceDraft",
    "BackupDraft",
    "ConnectedApi",
    "ConnectedCliError",
    "ConnectedCliErrorCode",
    "ConnectedCollection",
    "ConnectedRunReceipt",
    "ConnectedRunRequest",
    "ConnectedRunSettings",
    "DeletionDraft",
    "FeedbackDraft",
    "HttpConnectedApi",
    "ResultKind",
    "SecretGrantDraft",
    "append_assurance",
    "approve_deletion",
    "cancel_run",
    "check_health",
    "create_approval",
    "create_backup",
    "create_deletion",
    "decide_approval",
    "decide_finding",
    "execute_deletion",
    "fetch_events",
    "fetch_finding",
    "fetch_policies",
    "fetch_results",
    "fetch_run",
    "grant_secret",
    "hold_deletion",
    "new_idempotency_key",
    "parse_approval_arguments",
    "parse_connected_arguments",
    "parse_event_arguments",
    "parse_health_arguments",
    "parse_payload",
    "parse_results_arguments",
    "parse_run_arguments",
    "parse_single_argument",
    "read_approval",
    "read_assurance",
    "read_backup",
    "read_deletion",
    "read_feedback_metrics",
    "read_secret_grant",
    "render_receipt",
    "resumable_idempotency_key",
    "run_connected",
    "settings_from_environment",
    "submit_feedback",
    "timestamp",
    "transition_backup",
]
