"""Identity pin for the first-party deterministic scanner implementation."""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

from securecode_ai.contracts import ProducerRef

SCANNER_SOURCE_NAMES = (
    "product_scanner.py",
    "product_scanner_manifest.py",
    "product_rule_catalogue.py",
    "product_scanner_worker_common.py",
    "product_scanner_worker_ecmascript.py",
    "product_scanner_worker_go.py",
    "product_scanner_worker_python.py",
    "product_scanner_worker_support.py",
    "product_scanner_graph.py",
    "product_scanner_evidence.py",
    "cst.py",
    "cst_ecmascript.py",
    "cst_go.py",
    "cst_models.py",
    "cst_python.py",
    "cwe89.py",
    "cwe89_contracts.py",
    "cwe89_multilanguage.py",
    "cwe89_multilanguage_models.py",
    "cwe89_multilanguage_scanner.py",
    "cwe89_multilanguage_utilities.py",
    "cwe_portfolio.py",
    "cwe_portfolio_helpers.py",
    "cwe_portfolio_models.py",
    "ecmascript_cwe862.py",
    "go_cwe862.py",
    "python_cwe862.py",
    "ecmascript_cwe352.py",
    "ecmascript_cwe476.py",
    "ecmascript_cwe1321.py",
    "ecmascript_cwe22.py",
    "ecmascript_cwe295.py",
    "ecmascript_cwe1333.py",
    "ecmascript_cwe377.py",
    "ecmascript_cwe367.py",
    "ecmascript_cwe611.py",
    "ecmascript_cwe732.py",
    "ecmascript_cwe117.py",
    "ecmascript_cwe400.py",
    "ecmascript_cwe307.py",
    "ecmascript_cwe532.py",
    "ecmascript_cwe776.py",
    "ecmascript_cwe209.py",
    "ecmascript_cwe613.py",
    "ecmascript_cwe614.py",
    "ecmascript_cwe338.py",
    "ecmascript_cwe521.py",
    "ecmascript_cwe798.py",
    "ecmascript_cwe502.py",
    "ecmascript_cwe601.py",
    "ecmascript_cwe78.py",
    "ecmascript_cwe79.py",
    "ecmascript_cwe90.py",
    "ecmascript_cwe918.py",
    "ecmascript_cwe94.py",
    "ecmascript_cwe639.py",
    "ecmascript_cwe306.py",
    "go_cwe22.py",
    "go_cwe295.py",
    "go_cwe367.py",
    "go_cwe400.py",
    "go_cwe307.py",
    "go_cwe327.py",
    "go_cwe532.py",
    "go_cwe776.py",
    "go_cwe209.py",
    "go_cwe613.py",
    "go_cwe614.py",
    "go_cwe338.py",
    "go_cwe521.py",
    "go_cwe798.py",
    "go_cwe502.py",
    "go_cwe1333.py",
    "go_cwe601.py",
    "go_cwe78.py",
    "go_cwe79.py",
    "go_cwe90.py",
    "go_cwe918.py",
    "go_cwe_crypto.py",
    "go_cwe639.py",
    "go_cwe306.py",
    "go_cwe352.py",
    "go_cwe476.py",
    "go_cwe117.py",
    "go_cwe598.py",
    "python_ast.py",
    "python_cwe502.py",
    "python_cwe295.py",
    "python_cwe614.py",
    "python_cwe732.py",
    "python_cwe384.py",
    "python_cwe117.py",
    "python_cwe307.py",
    "python_cwe327.py",
    "python_cwe400.py",
    "python_cwe532.py",
    "python_cwe776.py",
    "python_cwe209.py",
    "python_cwe613.py",
    "python_cwe338.py",
    "python_cwe521.py",
    "python_cwe798.py",
    "python_cwe611.py",
    "python_cwe1333.py",
    "python_cwe601.py",
    "python_cwe78.py",
    "python_cwe79.py",
    "python_cwe90.py",
    "python_cwe918.py",
    "python_cwe94.py",
    "python_cwe639.py",
    "python_cwe306.py",
    "python_cwe352.py",
    "python_cwe476.py",
    "python_cwe598.py",
    "scanner_plugin.py",
)


def build_first_party_scanner_producer(source_root: Path) -> ProducerRef:
    """Build the scanner producer pin from the supplied package directory."""
    manifest = [
        (name, hashlib.sha256((source_root / name).read_bytes()).hexdigest())
        for name in SCANNER_SOURCE_NAMES
    ]
    digest = hashlib.sha256(json.dumps(manifest, separators=(",", ":")).encode()).hexdigest()
    return ProducerRef(
        schema_version="0.2.0",
        producer_id="securecode-first-party-static",
        producer_version="1.0.0",
        producer_sha256=digest,
    )
